# Generated by Django 2.0.2 on 2018-03-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64)),
                ('user_password', models.CharField(max_length=64)),
                ('user_img', models.CharField(max_length=256)),
                ('user_date', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('user_name', 'user_email'), ('user_name', 'user_password')},
        ),
    ]
