# Generated by Django 2.0.2 on 2018-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
