# Generated by Django 2.0.3 on 2018-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180318_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=64)),
                ('to_user', models.CharField(max_length=64)),
                ('number', models.IntegerField(max_length=10000, unique=True)),
                ('msg', models.CharField(max_length=8192)),
            ],
            options={
                'db_table': 'user_msg',
            },
        ),
    ]
