# Generated by Django 2.0.3 on 2018-03-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_usermsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermsg',
            name='number',
        ),
    ]
